"use strict";
var a;
a = 10;
a = "ola";
var b = 10;
var ct = { id: 0, nome: '', fone: '', email: '' };
ct.id = 10;
ct.nome = 'Jaqueline';
ct.email = "jaque@gmail.com";
ct.fone = '1234-2323';
console.log(ct);
